### ISSUE TITLE
Report a Bug Button

### ISSUE THREAD

**Issue by smkamranqadri** [circadiatech/reportabug-widget#4]
Report a Bug Button, by default it will be small and when mouse hovers happens it will be expanded.

<img width="595" alt="Screenshot 2021-10-30 at 2 05 08 PM" src="https://user-images.githubusercontent.com/13115396/139527002-dc423c42-aadb-4789-ae0b-04f692e13460.png">

**Comment by Tamsauce** [comment]
@smkamranqadri are you looking for the verbiage "report a bug" to increase in size during the hover?

**Comment by smkamranqadri** [comment]
I am sorry @Tamsauce someone else worked on it.

**Comment by Tamsauce** [comment]
No problem!  Is there anything else I might be able to help you with?
